/**
 * Parity with the server.
 *
 * `QCCheckList.validate` recomputes size, rate, net amount and the whole summary on
 * every push, so the server is the only authority on these numbers. Anywhere this app
 * disagrees, the operator watches a value change after syncing and stops trusting the
 * screen - which is precisely the failure mode the desktop client was built to fix.
 *
 * The fixtures are generated by running the real controller functions
 * (`_match_size`, `_touch_rate_map`, `group_checklist_rows`) against a seeded site, via
 * `scripts/generate_parity_fixtures.py`. Nothing here is hand-written expectation.
 */
import { describe, expect, it } from "vitest";

import fixtures from "./fixtures/parity.json";
import { cint, flt, pythonCompare } from "../electron/domain/frappeValues";
import { buildRateIndex, matchRate } from "../electron/domain/rates";
import { buildSizeIndex, findGaps, findOverlaps, matchSize } from "../electron/domain/sizing";
import { groupChecklistRows } from "../electron/domain/summary";
import type { ChecklistRow, SummaryRow } from "../electron/domain/summary";
import type { SkinTypeRange } from "../electron/domain/sizing";
import type { TouchRateDoc, TouchSizeDetail } from "../electron/domain/rates";

describe("size band resolution matches _match_size", () => {
	const index = buildSizeIndex(fixtures.sizing.ranges as SkinTypeRange[]);

	it.each(fixtures.sizing.cases)(
		"skin_type=$skin_type feetage=$feetage -> $expected",
		({ skin_type, feetage, expected }) => {
			expect(matchSize(index, skin_type, feetage)).toBe(expected);
		}
	);

	it("treats both band bounds as inclusive, as the Python does", () => {
		const onBoundary = fixtures.sizing.cases.filter((c) =>
			fixtures.sizing.ranges.some(
				(r) => r.skin_type === c.skin_type && (r.min_range === c.feetage || r.max_range === c.feetage)
			)
		);
		expect(onBoundary.length).toBeGreaterThan(0);
		for (const c of onBoundary) expect(matchSize(index, c.skin_type, c.feetage)).not.toBe("");
	});

	it("reports no overlapping bands in the seeded masters", () => {
		expect(findOverlaps(index)).toEqual([]);
	});

	it("detects a deliberately overlapping band", () => {
		const overlapping = buildSizeIndex([
			{ range_name: "Low", skin_type: "Cow", min_range: 5, max_range: 20, status: "Active" },
			{ range_name: "High", skin_type: "Cow", min_range: 15, max_range: 40, status: "Active" },
		]);
		expect(findOverlaps(overlapping)).toEqual([{ skin_type: "Cow", a: "Low", b: "High" }]);
	});

	it("detects a gap between bands", () => {
		const gapped = buildSizeIndex([
			{ range_name: "Low", skin_type: "Cow", min_range: 5, max_range: 10, status: "Active" },
			{ range_name: "High", skin_type: "Cow", min_range: 20, max_range: 40, status: "Active" },
		]);
		expect(findGaps(gapped)).toEqual([{ skin_type: "Cow", from: 10, to: 20 }]);
	});

	it("ignores inactive bands", () => {
		const withInactive = buildSizeIndex([
			{ range_name: "Retired", skin_type: "Cow", min_range: 5, max_range: 100, status: "Inactive" },
		]);
		expect(matchSize(withInactive, "Cow", 50)).toBe("");
	});
});

describe("touch rate resolution matches _touch_rate_map", () => {
	const index = buildRateIndex(
		fixtures.rates.rate_docs as TouchRateDoc[],
		fixtures.rates.size_details as TouchSizeDetail[]
	);

	it.each(fixtures.rates.cases)(
		"skin_type=$skin_type grade=$grade size=$size -> $expected",
		({ skin_type, grade, size, expected }) => {
			expect(matchRate(index, skin_type, grade, size)).toBe(expected);
		}
	);

	it("ignores a superseded Tounch Rate entirely, rather than falling back to it", () => {
		// The fixture seeds an older Cow/A sheet pricing Cow Large at 3. "Latest wins"
		// means the newer sheet's 165 applies - never the old sheet's number.
		const superseded = fixtures.rates.cases.find(
			(c) => c.skin_type === "Cow" && c.grade === "A" && c.size === "Cow Large"
		);
		expect(superseded?.expected).toBe(165);
		expect(matchRate(index, "Cow", "A", "Cow Large")).toBe(165);
		expect(matchRate(index, "Cow", "A", "Cow Large")).not.toBe(3);
	});

	it("returns 0 rather than throwing when any part of the key is missing", () => {
		expect(matchRate(index, null, "A", "Cow Small")).toBe(0);
		expect(matchRate(index, "Cow", null, "Cow Small")).toBe(0);
		expect(matchRate(index, "Cow", "A", null)).toBe(0);
	});

	it("yields 0 for every row when pricing is withheld by permlevel", () => {
		// What a Stock Manager receives: size details with no `tounch_rate` field at all.
		const withheld = buildRateIndex(
			fixtures.rates.rate_docs as TouchRateDoc[],
			(fixtures.rates.size_details as TouchSizeDetail[]).map(({ parent, size }) => ({ parent, size }))
		);
		expect(matchRate(withheld, "Cow", "A", "Cow Small")).toBe(0);
	});
});

describe("summary grouping matches group_checklist_rows", () => {
	const scenarios = Object.entries(
		fixtures.summary as Record<string, { rows: ChecklistRow[]; expected: SummaryRow[] }>
	);

	it.each(scenarios)("%s", (_label, { rows, expected }) => {
		expect(groupChecklistRows(rows)).toEqual(expected);
	});

	it("drops only Rejected rows, keeping blank and Accepted", () => {
		const { expected } = fixtures.summary.only_rejected_is_dropped;
		// two kept rows (8 + 7 feet), the Rejected 9 excluded
		expect(expected).toHaveLength(1);
		expect(expected[0]!.no_pieces).toBe(2);
		expect(expected[0]!.feetage).toBe(15);
	});

	it("orders by code point, not locale", () => {
		const order = fixtures.summary.case_sensitive_ordering.expected.map((r) => r.grade);
		expect(order).toEqual(["A", "B", "a", "b"]);
		// The desk script sorts this with localeCompare, which gives a different document.
		expect([...order].sort((a, b) => a.localeCompare(b))).not.toEqual(order);
		expect(groupChecklistRows(fixtures.summary.case_sensitive_ordering.rows).map((r) => r.grade)).toEqual(
			order
		);
	});

	it("keeps triples distinct when a name contains the separator character", () => {
		const rows = fixtures.summary.separator_collision.rows;
		expect(groupChecklistRows(rows)).toHaveLength(2);
	});
});

describe("flt and cint match Frappe", () => {
	it("strips thousands separators the way Frappe does", () => {
		expect(flt("1,234.5")).toBe(1234.5);
		// The fixture relies on this: flt("7,5") is 75, not 7.5.
		expect(flt("7,5")).toBe(75);
	});

	it("never yields NaN", () => {
		for (const value of ["", "abc", null, undefined, {}, [], NaN, Infinity]) {
			expect(Number.isFinite(flt(value))).toBe(true);
		}
	});

	it("truncates toward zero like Python int()", () => {
		expect(cint("2.9")).toBe(2);
		expect(cint(-2.9)).toBe(-2);
		expect(cint(null)).toBe(0);
	});

	it("orders strings by code point", () => {
		expect(["a", "B", "A", "b"].sort(pythonCompare)).toEqual(["A", "B", "a", "b"]);
		expect(["Z", "Ä", "A"].sort(pythonCompare)).toEqual(["A", "Z", "Ä"]);
	});
});
