/**
 * Summary rollup: the client-side port of `group_checklist_rows` in
 * `slw/slw/doctype/qc_check_list/qc_check_list.py`.
 *
 * The Python docstring records that this grouping once existed as three separate
 * client-side implementations that disagreed on the key and on which rows to skip, so
 * the numbers you got depended on the page you came from. This is a fourth
 * implementation, which is only defensible because `summary.test.ts` asserts it against
 * fixtures generated by the Python itself.
 *
 * Two rules are easy to get wrong and are both deliberate here:
 *
 *   - Only rows explicitly marked "Rejected" are dropped. A blank status means the hide
 *     has not been judged yet, not that it failed. The desk script instead drops any row
 *     whose status is set and is not "Accepted"; the server's rule is the one that
 *     persists, so the server's rule is the one implemented.
 *
 *   - The output is ordered by Python's tuple sort over (grade, skin_type, size), which
 *     compares code points. The desk script uses localeCompare, which orders a
 *     mixed-case summary differently from the document that actually gets saved.
 */
import { cint, flt, pythonCompare } from "./frappeValues";

export interface ChecklistRow {
	item_code?: string | null;
	item_name?: string | null;
	skin_type?: string | null;
	grade?: string | null;
	size?: string | null;
	status?: string | null;
	feetage?: unknown;
	no_pieces?: unknown;
}

export interface SummaryRow {
	grade: string;
	skin_type: string;
	size: string;
	item_code: string;
	item_name: string;
	no_pieces: number;
	feetage: number;
}

export function groupChecklistRows(rows: readonly ChecklistRow[] | null | undefined): SummaryRow[] {
	const groups = new Map<string, SummaryRow>();

	for (const item of rows ?? []) {
		if (item.status === "Rejected") continue;

		const grade = item.grade ?? "";
		const skinType = item.skin_type ?? "";
		const size = item.size ?? "";
		// NUL separator, because range names routinely contain spaces ("Cow Small").
		// Joined on a space, grade "A" / skin "Cow Small" / size "X" would collide with
		// grade "A" / skin "Cow" / size "Small X", silently merging two groups' piece
		// counts into one line. The Python keys on a tuple and cannot hit this.
		const key = [grade, skinType, size].join("\u0000");

		let group = groups.get(key);
		if (!group) {
			group = {
				grade,
				skin_type: skinType,
				size,
				item_code: item.item_code ?? "",
				item_name: item.item_name ?? "",
				no_pieces: 0,
				feetage: 0,
			};
			groups.set(key, group);
		}

		group.no_pieces += cint(item.no_pieces);
		group.feetage += flt(item.feetage);
	}

	return [...groups.values()].sort(
		(a, b) =>
			pythonCompare(a.grade, b.grade) ||
			pythonCompare(a.skin_type, b.skin_type) ||
			pythonCompare(a.size, b.size)
	);
}

/** Advisory only: the server recomputes `grand_total` from its own resolved rates. */
export function grandTotal(rows: readonly { feetage?: unknown; rate?: unknown }[]): number {
	let total = 0;
	for (const row of rows) total += flt(row.feetage) * flt(row.rate);
	return total;
}
